# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  project-app:
    image: project
    depends_on:
      - project-postgresql
    restart: unless-stopped
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://project-postgresql:5432/project
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://project-postgresql:5432/project
      - JHIPSTER_SLEEP=10
      - SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE=400MB
      - SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE=400MB
      - JHIPSTER_CORS_ALLOW-CREDENTIALS=true
      - JHIPSTER_CORS_ALLOW-ORIGINS=*
    ports:
      - 8084:8080
    volumes:
      - project_data:/media
  project-postgresql:
    image: postgres:14.5
    volumes:
      - bd_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=project
      - POSTGRES_PASSWORD=1dm3n3str1d4r
      - POSTGRES_DB=project
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432

volumes:
  bd_data:
  project_data:
